
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace home.insurance.cn.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Order_ItemInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order_ItemInfo()
    {

        this.Order_PolicyHolder = new HashSet<Order_PolicyHolder>();

    }


    public int ID { get; set; }

    public Nullable<int> OrderID { get; set; }

    public Nullable<byte> Channel { get; set; }

    public string ProductId { get; set; }

    public Nullable<decimal> AmountPayable { get; set; }

    public string Memo { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string ProductName { get; set; }

    public string PlanId { get; set; }



    public virtual Order_BaseInfo Order_BaseInfo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order_PolicyHolder> Order_PolicyHolder { get; set; }

}

}
