
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace home.insurance.cn.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Order_PolicyHolder
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order_PolicyHolder()
    {

        this.Order_InsuredPerson = new HashSet<Order_InsuredPerson>();

    }


    public int ID { get; set; }

    public string DomainOrderId { get; set; }

    public Nullable<int> PolicyType { get; set; }

    public string ProductId { get; set; }

    public string PlanId { get; set; }

    public Nullable<System.DateTime> OperateDate { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<int> ProposalNum { get; set; }

    public Nullable<int> RationCount { get; set; }

    public Nullable<decimal> PersonalAmount { get; set; }

    public Nullable<decimal> PersonalPremium { get; set; }

    public Nullable<decimal> SumAmount { get; set; }

    public Nullable<decimal> SumPremium { get; set; }

    public string PolicyholderName { get; set; }

    public string IdentifyType { get; set; }

    public string IdentifyNumber { get; set; }

    public string Sex { get; set; }

    public string TelPhone { get; set; }

    public string SendSMS { get; set; }

    public string Mobile { get; set; }

    public Nullable<int> OrderItemID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order_InsuredPerson> Order_InsuredPerson { get; set; }

    public virtual Order_ItemInfo Order_ItemInfo { get; set; }

}

}
